"""Supabase authentication service for YAffiliate."""

from __future__ import annotations

from typing import Any

from app.services.supabase_service import SupabaseService


class AuthService:
    """Handle YAffiliate user authentication with Supabase Auth."""

    def __init__(self) -> None:
        """Initialize the Supabase authentication client."""
        self.supabase = SupabaseService()
        self.client = self.supabase.client

    def sign_up(
        self,
        email: str,
        password: str,
    ) -> Any:
        """Create a new user with email and password."""

        cleaned_email = email.strip().lower()

        if not cleaned_email:
            raise ValueError("Email is required.")

        if not password:
            raise ValueError("Password is required.")

        if len(password) < 6:
            raise ValueError(
                "Password must contain at least 6 characters."
            )

        try:
            response = self.client.auth.sign_up(
                {
                    "email": cleaned_email,
                    "password": password,
                }
            )

            user = getattr(response, "user", None)

            # Supabase can hide whether an email already exists.
            # In some configurations it returns a user object with
            # no identities instead of raising an explicit exception.
            if user is not None:
                identities = getattr(user, "identities", None)

                if identities == []:
                    raise ValueError(
                        "An account with this email already exists. "
                        "Please sign in instead."
                    )

            return response

        except ValueError:
            # Preserve validation errors generated by this service.
            raise

        except Exception as exc:
            # Keep the original message for diagnosis.
            original_message = str(exc)
            message = original_message.lower()

            # Handle common Supabase duplicate-user responses.
            duplicate_messages = (
                "user already registered",
                "already registered",
                "already exists",
                "email already",
            )

            if any(
                text in message
                for text in duplicate_messages
            ):
                raise ValueError(
                    "An account with this email already exists. "
                    "Please sign in instead."
                ) from exc

            # TEMPORARY DEBUGGING:
            # Show the real Supabase error so we can identify exactly
            # why account creation is failing.
            raise ValueError(
                f"Supabase signup error: {original_message}"
            ) from exc

    def sign_in(
        self,
        email: str,
        password: str,
    ) -> Any:
        """Sign in an existing user with email and password."""

        cleaned_email = email.strip().lower()

        if not cleaned_email:
            raise ValueError("Email is required.")

        if not password:
            raise ValueError("Password is required.")

        try:
            return self.client.auth.sign_in_with_password(
                {
                    "email": cleaned_email,
                    "password": password,
                }
            )

        except Exception as exc:
            message = str(exc).lower()

            if "email not confirmed" in message:
                raise ValueError(
                    "Please confirm your email address before signing in."
                ) from exc

            invalid_login_messages = (
                "invalid login credentials",
                "invalid credentials",
            )

            if any(
                text in message
                for text in invalid_login_messages
            ):
                raise ValueError(
                    "Incorrect email or password."
                ) from exc

            raise ValueError(
                "We could not sign you in. Please try again."
            ) from exc

    def sign_out(self) -> None:
        """Sign out the currently authenticated user."""

        try:
            self.client.auth.sign_out()

        except Exception as exc:
            raise ValueError(
                "We could not sign you out. Please try again."
            ) from exc

    def get_current_user(self) -> Any | None:
        """Return the verified current Supabase user, if available."""

        try:
            response = self.client.auth.get_user()

        except Exception:
            return None

        return getattr(response, "user", None)

    def get_current_user_id(self) -> str | None:
        """Return the authenticated user's UUID."""

        user = self.get_current_user()

        if user is None:
            return None

        user_id = getattr(user, "id", None)

        return str(user_id) if user_id else None

    def get_current_user_email(self) -> str | None:
        """Return the authenticated user's email address."""

        user = self.get_current_user()

        if user is None:
            return None

        email = getattr(user, "email", None)

        return str(email) if email else None

    def is_authenticated(self) -> bool:
        """Return True when a verified authenticated user exists."""

        return self.get_current_user() is not None