"""Artificial Intelligence assistant page for Filtrify.

This page uses Filtrify's central Artificial Intelligence service to generate
structured analysis and drafting support.

AI means Artificial Intelligence.
"""
from __future__ import annotations
from app.services.translation_service import ui
import streamlit as st
from app.components.layout import page_header
from app.services.ai import ai_service, configure_ai_service

def render() -> None:
    """Render the Artificial Intelligence workspace page."""
    page_header('AI workspace', 'Turn structured research into better decisions.', 'Analysis and drafting with human review before publication or spending.')
    mode = st.selectbox(ui('Assistant mode'), ['Product analysis', 'Campaign diagnosis', 'Landing-page outline', 'Keyword clustering', 'Weekly action plan'])
    context = st.text_area(ui('Context'), height=220)
    generate_analysis = st.button(ui('Generate analysis'), type='primary', use_container_width=True)
    if not generate_analysis:
        return
    if not context.strip():
        st.error(ui('Provide context first.'))
        return
    try:
        _ensure_ai_service_is_configured()
        with st.spinner('Generating analysis...'):
            response = ai_service.generate_text(system_prompt='You are an expert affiliate-marketing analyst working inside Filtrify. Be precise, separate facts from assumptions, and never fabricate performance data. Clearly identify missing information and avoid presenting estimates as confirmed facts.', prompt=f'Assistant mode: {mode}\n\nContext:\n{context.strip()}', temperature=0.3, maximum_output_tokens=2000, metadata={'page': 'ai_assistant', 'assistant_mode': mode})
        if not response.success:
            st.error(response.message or 'The analysis could not be generated.')
            return
        generated_content = response.content.strip()
        if not generated_content:
            st.error(ui('The Artificial Intelligence provider returned an empty response.'))
            return
        st.markdown('### Generated analysis')
        st.markdown(generated_content)
        provider_details = response.provider_name
        if response.model_name:
            provider_details += f' · Model: {response.model_name}'
        st.caption(f'Generated by {provider_details}. Review the result before acting on it.')
    except Exception as error:
        st.error(f'The Artificial Intelligence analysis could not be generated. {error}')

def _ensure_ai_service_is_configured() -> None:
    """Configure the shared Artificial Intelligence service when required.

    Raises:
        RuntimeError:
            If Filtrify cannot find a valid provider configuration.
    """
    if ai_service.has_provider:
        return
    configured = configure_ai_service(ai_service)
    if not configured:
        raise RuntimeError('No Artificial Intelligence provider is configured. Confirm that OPENAI_API_KEY exists in the local .env file.')
