"""Provider-independent Artificial Intelligence definitions for Filtrify.

A provider is the external service responsible for generating text, such as
OpenAI, Anthropic, Google Gemini, or a locally hosted model.

This module defines the common interface every provider must follow.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Mapping


@dataclass(frozen=True)
class AIProviderRequest:
    """Information sent to an Artificial Intelligence provider.

    Attributes:
        prompt:
            Main instructions and content sent to the model.

        system_prompt:
            Higher-level instructions describing how the model should behave.

        model:
            Optional provider-specific model name.

        temperature:
            Controls how predictable or creative the response should be.
            Lower values generally produce more consistent results.

        maximum_output_tokens:
            Maximum number of tokens the provider may generate. A token is a
            small unit of text processed by an Artificial Intelligence model.

        metadata:
            Additional values that may be useful to a provider.
    """

    prompt: str
    system_prompt: str | None = None
    model: str | None = None
    temperature: float = 0.4
    maximum_output_tokens: int | None = None
    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )


@dataclass(frozen=True)
class AIProviderResponse:
    """Standard result returned by an Artificial Intelligence provider.

    Attributes:
        content:
            Text generated by the provider.

        provider_name:
            Name of the provider that handled the request.

        model_name:
            Name of the model used to generate the response.

        success:
            Indicates whether generation completed successfully.

        message:
            Optional success, warning, or error message.

        input_tokens:
            Number of tokens processed from the request, when available.

        output_tokens:
            Number of tokens generated in the response, when available.

        metadata:
            Additional provider-specific response information.
    """

    content: str
    provider_name: str
    model_name: str | None = None
    success: bool = True
    message: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )


class AIProvider(ABC):
    """Abstract base class for every Filtrify AI provider.

    AI means Artificial Intelligence.

    Concrete providers must implement the ``generate`` method while returning
    the same ``AIProviderResponse`` structure.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Return the provider's unique internal name."""

    @property
    def default_model(self) -> str | None:
        """Return the model used when no model is supplied."""

        return None

    @abstractmethod
    def generate(
        self,
        request: AIProviderRequest,
    ) -> AIProviderResponse:
        """Generate content using the provider.

        Args:
            request:
                Validated generation instructions.

        Returns:
            A standardized provider response.
        """

    def validate_request(
        self,
        request: AIProviderRequest,
    ) -> AIProviderRequest:
        """Validate an Artificial Intelligence provider request.

        Args:
            request:
                Provider request that should be validated.

        Returns:
            The validated request.

        Raises:
            TypeError:
                If the request has an unsupported type.

            ValueError:
                If required information is missing or invalid.
        """

        if not isinstance(
            request,
            AIProviderRequest,
        ):
            raise TypeError(
                "The provider request must be an "
                "AIProviderRequest instance."
            )

        if not request.prompt.strip():
            raise ValueError(
                "The provider prompt cannot be empty."
            )

        if not 0.0 <= request.temperature <= 2.0:
            raise ValueError(
                "The provider temperature must be "
                "between 0.0 and 2.0."
            )

        if (
            request.maximum_output_tokens is not None
            and request.maximum_output_tokens < 1
        ):
            raise ValueError(
                "Maximum output tokens must be at "
                "least 1."
            )

        return request

    def __repr__(self) -> str:
        """Return a developer-friendly provider representation."""

        return (
            f"{self.__class__.__name__}("
            f"name={self.name!r}, "
            f"default_model={self.default_model!r}"
            f")"
        )