"""Central Artificial Intelligence service for Filtrify.

The service provides one consistent interface for generating content,
regardless of whether Filtrify uses OpenAI, Anthropic, Google Gemini, a local
model, or another provider.

AI means Artificial Intelligence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping

from app.services.ai.ai_provider import (
    AIProvider,
    AIProviderRequest,
    AIProviderResponse,
)


@dataclass(frozen=True)
class AIServiceRequest:
    """Information supplied to the Filtrify Artificial Intelligence service.

    Attributes:
        prompt:
            Main instructions and source content sent to the provider.

        system_prompt:
            Higher-level instructions describing the model's role and
            behaviour.

        model:
            Optional model name. When omitted, the provider's default model
            will be used.

        temperature:
            Controls how consistent or creative the generated result should
            be. Lower values generally produce more predictable responses.

        maximum_output_tokens:
            Maximum number of tokens that the provider may generate. A token
            is a small unit of text processed by an Artificial Intelligence
            model.

        metadata:
            Additional information that may be useful to the provider or
            application.
    """

    prompt: str
    system_prompt: str | None = None
    model: str | None = None
    temperature: float = 0.4
    maximum_output_tokens: int | None = None
    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )


@dataclass(frozen=True)
class AIServiceResponse:
    """Standard response returned by the Artificial Intelligence service.

    Attributes:
        content:
            Text generated by the selected provider.

        success:
            Indicates whether generation completed successfully.

        provider_name:
            Name of the provider that handled the request.

        model_name:
            Name of the model used to generate the response.

        message:
            Optional success, warning, or error message.

        input_tokens:
            Number of input tokens processed, when supplied by the provider.

        output_tokens:
            Number of output tokens generated, when supplied by the provider.

        metadata:
            Additional application or provider information.
    """

    content: str
    success: bool
    provider_name: str
    model_name: str | None = None
    message: str | None = None
    input_tokens: int | None = None
    output_tokens: int | None = None
    metadata: Mapping[str, Any] = field(
        default_factory=dict
    )


class AIService:
    """Generate content through a configured Artificial Intelligence provider.

    The service separates Filtrify's actions from provider-specific code.
    Actions send a standard request to this class, and this class delegates
    generation to the configured provider.
    """

    def __init__(
        self,
        provider: AIProvider | None = None,
    ) -> None:
        """Initialize the service.

        Args:
            provider:
                Artificial Intelligence provider that should handle generation.
                A provider may also be assigned later using ``set_provider``.
        """

        self._provider = provider

    @property
    def provider(self) -> AIProvider | None:
        """Return the currently configured provider."""

        return self._provider

    @property
    def has_provider(self) -> bool:
        """Return whether a provider has been configured."""

        return self._provider is not None

    def set_provider(
        self,
        provider: AIProvider,
    ) -> None:
        """Assign the provider used for future requests.

        Args:
            provider:
                Provider instance that should handle generation.

        Raises:
            TypeError:
                If the supplied value does not inherit from ``AIProvider``.
        """

        if not isinstance(provider, AIProvider):
            raise TypeError(
                "The Artificial Intelligence service provider "
                "must inherit from AIProvider."
            )

        self._provider = provider

    def clear_provider(self) -> None:
        """Remove the currently configured provider."""

        self._provider = None

    def generate(
        self,
        request: AIServiceRequest,
    ) -> AIServiceResponse:
        """Generate content through the configured provider.

        Args:
            request:
                Standard Filtrify generation request.

        Returns:
            A standardized service response.

        Raises:
            TypeError:
                If the request has an unsupported type.

            RuntimeError:
                If no provider has been configured.
        """

        validated_request = self.validate_request(
            request
        )

        provider = self._require_provider()

        provider_request = AIProviderRequest(
            prompt=validated_request.prompt,
            system_prompt=(
                validated_request.system_prompt
            ),
            model=validated_request.model,
            temperature=validated_request.temperature,
            maximum_output_tokens=(
                validated_request.maximum_output_tokens
            ),
            metadata=validated_request.metadata,
        )

        provider_response = provider.generate(
            provider_request
        )

        return self._convert_provider_response(
            provider_response
        )

    def generate_text(
        self,
        *,
        prompt: str,
        system_prompt: str | None = None,
        model: str | None = None,
        temperature: float = 0.4,
        maximum_output_tokens: int | None = None,
        metadata: Mapping[str, Any] | None = None,
    ) -> AIServiceResponse:
        """Generate text using convenient keyword arguments.

        This method is a shorter alternative to manually creating an
        ``AIServiceRequest``.

        Args:
            prompt:
                Main generation instructions.

            system_prompt:
                Higher-level instructions describing the model's role.

            model:
                Optional model name.

            temperature:
                Controls response consistency or creativity.

            maximum_output_tokens:
                Maximum number of output tokens.

            metadata:
                Optional additional request information.

        Returns:
            A standardized service response.
        """

        return self.generate(
            AIServiceRequest(
                prompt=prompt,
                system_prompt=system_prompt,
                model=model,
                temperature=temperature,
                maximum_output_tokens=(
                    maximum_output_tokens
                ),
                metadata=metadata or {},
            )
        )

    def validate_request(
        self,
        request: AIServiceRequest,
    ) -> AIServiceRequest:
        """Validate a service request.

        Args:
            request:
                Request that should be validated.

        Returns:
            The validated request.

        Raises:
            TypeError:
                If the request is not an ``AIServiceRequest``.

            ValueError:
                If required request values are missing or invalid.
        """

        if not isinstance(
            request,
            AIServiceRequest,
        ):
            raise TypeError(
                "The Artificial Intelligence service request "
                "must be an AIServiceRequest instance."
            )

        if not isinstance(request.prompt, str):
            raise TypeError(
                "The Artificial Intelligence prompt "
                "must be a string."
            )

        if not request.prompt.strip():
            raise ValueError(
                "The Artificial Intelligence prompt "
                "cannot be empty."
            )

        if not 0.0 <= request.temperature <= 2.0:
            raise ValueError(
                "The Artificial Intelligence temperature "
                "must be between 0.0 and 2.0."
            )

        if (
            request.maximum_output_tokens is not None
            and request.maximum_output_tokens < 1
        ):
            raise ValueError(
                "Maximum output tokens must be at least 1."
            )

        return request

    def _require_provider(self) -> AIProvider:
        """Return the configured provider.

        Raises:
            RuntimeError:
                If no provider has been configured.
        """

        if self._provider is None:
            raise RuntimeError(
                "No Artificial Intelligence provider has "
                "been configured for Filtrify."
            )

        return self._provider

    @staticmethod
    def _convert_provider_response(
        response: AIProviderResponse,
    ) -> AIServiceResponse:
        """Convert a provider response into a service response.

        Args:
            response:
                Standard provider response.

        Returns:
            Standard Filtrify service response.

        Raises:
            TypeError:
                If the provider returned an unsupported result.
        """

        if not isinstance(
            response,
            AIProviderResponse,
        ):
            raise TypeError(
                "The Artificial Intelligence provider must "
                "return an AIProviderResponse instance."
            )

        return AIServiceResponse(
            content=response.content,
            success=response.success,
            provider_name=response.provider_name,
            model_name=response.model_name,
            message=response.message,
            input_tokens=response.input_tokens,
            output_tokens=response.output_tokens,
            metadata=response.metadata,
        )

    def __repr__(self) -> str:
        """Return a developer-friendly service representation."""

        provider_name = (
            self._provider.name
            if self._provider is not None
            else None
        )

        return (
            f"{self.__class__.__name__}("
            f"provider={provider_name!r}"
            f")"
        )


ai_service = AIService()